import { publicUrl } from "./commons";
export const javaTechnologiesPortfolio = [
    {
        id: 1,
        title: "Java 8",
        img: publicUrl("/assets/skills/JAVA8.png"),
        // img: "https://miro.medium.com/max/1140/0*BbNzc9erdOsSolt1.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 2,
        title: "Servlets",
        img: publicUrl("/assets/skills/SERVLETS.png"),
        // img: "http://10minbasics.com/wp-content/uploads/2016/03/servlets-logo.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 3,
        title: "Spring MVC",
        img: publicUrl("/assets/skills/SPRING.png"),
        // img: "https://javainterviewpoint.azureedge.net/wp-content/uploads/2019/02/Spring-MVC-Tutorial.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 4,
        title: "Hibernate",
        img: publicUrl("/assets/skills/HIBERNATE.png"),
        // img: "https://miro.medium.com/max/796/1*zZNZ0iipbKwx0z_niqcY9w.png?compress=1&resize=1200x900",
        value: 3,
    },
];

export const webDevelopmentPortfolio = [
    {
        id: 1,
        title: "HTML5",
        img: publicUrl("/assets/skills/HTML5.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919827.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 2,
        title: "CSS",
        img: publicUrl("/assets/skills/CSS3.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919826.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 3,
        title: "JavaScript",
        img: publicUrl("/assets/skills/JAVASCRIPT.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919828.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 4,
        title: "AngularJS",
        img: publicUrl("/assets/skills/ANGULAR7.png"),
        // img: "https://www.seekpng.com/png/detail/53-536700_learn-angular-4-from-scratch-angularjs-mastery-a.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 5,
        title: "Angular 7",
        img: publicUrl("/assets/skills/ANGULARJS.png"),
        // img: "https://www.glocalview.com/wp-content/uploads/2020/03/angular-7.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 6,
        title: "Node.js",
        img: publicUrl("/assets/skills/NODEJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 7,
        title: "Restful Web Services",
        img: publicUrl("/assets/skills/RESTFUL.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 8,
        title: "Express.js",
        img: publicUrl("/assets/skills/EXPRESSJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 1,
        title: "HTML5",
        img: publicUrl("/assets/skills/HTML5.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919827.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 2,
        title: "CSS",
        img: publicUrl("/assets/skills/CSS3.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919826.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 3,
        title: "JavaScript",
        img: publicUrl("/assets/skills/JAVASCRIPT.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919828.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 4,
        title: "AngularJS",
        img: publicUrl("/assets/skills/ANGULAR7.png"),
        // img: "https://www.seekpng.com/png/detail/53-536700_learn-angular-4-from-scratch-angularjs-mastery-a.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 5,
        title: "Angular 7",
        img: publicUrl("/assets/skills/ANGULARJS.png"),
        // img: "https://www.glocalview.com/wp-content/uploads/2020/03/angular-7.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 6,
        title: "Node.js",
        img: publicUrl("/assets/skills/NODEJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 7,
        title: "Restful Web Services",
        img: publicUrl("/assets/skills/RESTFUL.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 8,
        title: "Express.js",
        img: publicUrl("/assets/skills/EXPRESSJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 1,
        title: "HTML5",
        img: publicUrl("/assets/skills/HTML5.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919827.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 2,
        title: "CSS",
        img: publicUrl("/assets/skills/CSS3.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919826.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 3,
        title: "JavaScript",
        img: publicUrl("/assets/skills/JAVASCRIPT.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919828.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 4,
        title: "AngularJS",
        img: publicUrl("/assets/skills/ANGULAR7.png"),
        // img: "https://www.seekpng.com/png/detail/53-536700_learn-angular-4-from-scratch-angularjs-mastery-a.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 5,
        title: "Angular 7",
        img: publicUrl("/assets/skills/ANGULARJS.png"),
        // img: "https://www.glocalview.com/wp-content/uploads/2020/03/angular-7.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 6,
        title: "Node.js",
        img: publicUrl("/assets/skills/NODEJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 7,
        title: "Restful Web Services",
        img: publicUrl("/assets/skills/RESTFUL.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 8,
        title: "Express.js",
        img: publicUrl("/assets/skills/EXPRESSJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 1,
        title: "HTML5",
        img: publicUrl("/assets/skills/HTML5.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919827.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 2,
        title: "CSS",
        img: publicUrl("/assets/skills/CSS3.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919826.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 3,
        title: "JavaScript",
        img: publicUrl("/assets/skills/JAVASCRIPT.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919828.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 4,
        title: "AngularJS",
        img: publicUrl("/assets/skills/ANGULAR7.png"),
        // img: "https://www.seekpng.com/png/detail/53-536700_learn-angular-4-from-scratch-angularjs-mastery-a.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 5,
        title: "Angular 7",
        img: publicUrl("/assets/skills/ANGULARJS.png"),
        // img: "https://www.glocalview.com/wp-content/uploads/2020/03/angular-7.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 6,
        title: "Node.js",
        img: publicUrl("/assets/skills/NODEJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 7,
        title: "Restful Web Services",
        img: publicUrl("/assets/skills/RESTFUL.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 8,
        title: "Express.js",
        img: publicUrl("/assets/skills/EXPRESSJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 1,
        title: "HTML5",
        img: publicUrl("/assets/skills/HTML5.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919827.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 2,
        title: "CSS",
        img: publicUrl("/assets/skills/CSS3.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919826.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 3,
        title: "JavaScript",
        img: publicUrl("/assets/skills/JAVASCRIPT.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919828.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 4,
        title: "AngularJS",
        img: publicUrl("/assets/skills/ANGULAR7.png"),
        // img: "https://www.seekpng.com/png/detail/53-536700_learn-angular-4-from-scratch-angularjs-mastery-a.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 5,
        title: "Angular 7",
        img: publicUrl("/assets/skills/ANGULARJS.png"),
        // img: "https://www.glocalview.com/wp-content/uploads/2020/03/angular-7.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 6,
        title: "Node.js",
        img: publicUrl("/assets/skills/NODEJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 7,
        title: "Restful Web Services",
        img: publicUrl("/assets/skills/RESTFUL.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 8,
        title: "Express.js",
        img: publicUrl("/assets/skills/EXPRESSJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 1,
        title: "HTML5",
        img: publicUrl("/assets/skills/HTML5.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919827.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 2,
        title: "CSS",
        img: publicUrl("/assets/skills/CSS3.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919826.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 3,
        title: "JavaScript",
        img: publicUrl("/assets/skills/JAVASCRIPT.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919828.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 4,
        title: "AngularJS",
        img: publicUrl("/assets/skills/ANGULAR7.png"),
        // img: "https://www.seekpng.com/png/detail/53-536700_learn-angular-4-from-scratch-angularjs-mastery-a.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 5,
        title: "Angular 7",
        img: publicUrl("/assets/skills/ANGULARJS.png"),
        // img: "https://www.glocalview.com/wp-content/uploads/2020/03/angular-7.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 6,
        title: "Node.js",
        img: publicUrl("/assets/skills/NODEJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 7,
        title: "Restful Web Services",
        img: publicUrl("/assets/skills/RESTFUL.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 8,
        title: "Express.js",
        img: publicUrl("/assets/skills/EXPRESSJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 1,
        title: "HTML5",
        img: publicUrl("/assets/skills/HTML5.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919827.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 2,
        title: "CSS",
        img: publicUrl("/assets/skills/CSS3.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919826.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 3,
        title: "JavaScript",
        img: publicUrl("/assets/skills/JAVASCRIPT.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919828.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 4,
        title: "AngularJS",
        img: publicUrl("/assets/skills/ANGULAR7.png"),
        // img: "https://www.seekpng.com/png/detail/53-536700_learn-angular-4-from-scratch-angularjs-mastery-a.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 5,
        title: "Angular 7",
        img: publicUrl("/assets/skills/ANGULARJS.png"),
        // img: "https://www.glocalview.com/wp-content/uploads/2020/03/angular-7.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 6,
        title: "Node.js",
        img: publicUrl("/assets/skills/NODEJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 7,
        title: "Restful Web Services",
        img: publicUrl("/assets/skills/RESTFUL.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 8,
        title: "Express.js",
        img: publicUrl("/assets/skills/EXPRESSJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 1,
        title: "HTML5",
        img: publicUrl("/assets/skills/HTML5.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919827.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 2,
        title: "CSS",
        img: publicUrl("/assets/skills/CSS3.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919826.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 3,
        title: "JavaScript",
        img: publicUrl("/assets/skills/JAVASCRIPT.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919828.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 4,
        title: "AngularJS",
        img: publicUrl("/assets/skills/ANGULAR7.png"),
        // img: "https://www.seekpng.com/png/detail/53-536700_learn-angular-4-from-scratch-angularjs-mastery-a.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 5,
        title: "Angular 7",
        img: publicUrl("/assets/skills/ANGULARJS.png"),
        // img: "https://www.glocalview.com/wp-content/uploads/2020/03/angular-7.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 6,
        title: "Node.js",
        img: publicUrl("/assets/skills/NODEJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 7,
        title: "Restful Web Services",
        img: publicUrl("/assets/skills/RESTFUL.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 8,
        title: "Express.js",
        img: publicUrl("/assets/skills/EXPRESSJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 1,
        title: "HTML5",
        img: publicUrl("/assets/skills/HTML5.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919827.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 2,
        title: "CSS",
        img: publicUrl("/assets/skills/CSS3.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919826.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 3,
        title: "JavaScript",
        img: publicUrl("/assets/skills/JAVASCRIPT.png"),
        // img: "https://image.flaticon.com/icons/png/512/919/919828.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 4,
        title: "AngularJS",
        img: publicUrl("/assets/skills/ANGULAR7.png"),
        // img: "https://www.seekpng.com/png/detail/53-536700_learn-angular-4-from-scratch-angularjs-mastery-a.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 5,
        title: "Angular 7",
        img: publicUrl("/assets/skills/ANGULARJS.png"),
        // img: "https://www.glocalview.com/wp-content/uploads/2020/03/angular-7.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 6,
        title: "Node.js",
        img: publicUrl("/assets/skills/NODEJS.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 2.5,
    },
    {
        id: 7,
        title: "Restful Web Services",
        img: publicUrl("/assets/skills/RESTFUL.png"),
        // img: "https://image.flaticon.com/icons/png/128/919/919825.png?compress=1&resize=1200x900",
        value: 4,
    },
];

export const databasePortfolio = [
    {
        id: 1,
        title: "Cassandra",
        img: publicUrl("/assets/skills/CASSANDRA.png"),
        // img: "https://download.logo.wine/logo/Apache_Cassandra/Apache_Cassandra-Logo.wine.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 2,
        title: "MySQL",
        img: publicUrl("/assets/skills/MYSQL.png"),
        // img: "https://download.logo.wine/logo/MySQL/MySQL-Logo.wine.png?compress=1&resize=1200x900",
        value: 4,
    },
    {
        id: 3,
        title: "Oracle",
        img: publicUrl("/assets/skills/ORACLE.png"),
        // img: "https://mpng.subpng.com/20181024/wv/kisspng-logo-sail-racing-oracle-tee-grey-violet-brand-font-database-page-3-of-5-azoft-5bd0f1e6f2a5b0.3615376615404200709939.jpg?compress=1&resize=1200x900",
        value: 4,
    },
];

export const dotnetPortfolio = [
    {
        id: 1,
        title: "C#",
        img: publicUrl("/assets/skills/CSHARP.png"),
        // img: "https://miro.medium.com/max/1200/1*w0u2TZpEp3WfKMrlL5jTSw.png?compress=1&resize=1200x900",
        value: 3,
    },
    {
        id: 2,
        title: ".NET",
        img: publicUrl("/assets/skills/DOTNET.png"),
        // img: "https://www.logolynx.com/images/logolynx/85/85fa91d685f6b4e0b6aaf15acab5c5a0.jpeg?compress=1&resize=1200x900",
        value: 3,
    },
];

export const progLangsPortfolio = [
    {
        id: 1,
        title: "C",
        img: publicUrl("/assets/skills/C-PROGRAMMING.png"),
        // img: "https://e7.pngegg.com/pngimages/465/779/png-clipart-blue-and-white-c-logo-the-c-programming-language-computer-programming-computer-icons-programmer-blue-angle.png?compress=1&resize=1200x900",
        value: 4,
    },
    // {
    //     id: 2,
    //     title: "C++",
    //     img: publicUrl("/assets/skills/CPP-PROGRAMMING.png"),
    //     // img: "https://image.flaticon.com/icons/png/128/74/74897.png?compress=1&resize=1200x900",
    //     value: 4,
    // },
    // {
    //     id: 3,
    //     title: "Python",
    //     img: publicUrl("/assets/skills/PYTHON.png"),
    //     // img: "https://mpng.subpng.com/20180825/box/kisspng-python-programming-language-computer-programming-c-hanuman-png-transparent-images-free-download-clip-5b814ed3233799.3867698615352009791443.jpg?compress=1&resize=1200x900",
    //     value: 4,
    // },
];
